services:
  signal-client:
    image: chase295/miam-signal:latest
    restart: unless-stopped
    environment:
      # IoT Orchestrator
      WS_HOST: "XXX"              # IoT Orchestrator Host (BITTE ANPASSEN)
      WS_PORT: 8080                      # WebSocket Gateway Port
      WS_PATH: "/ws/external"           # WebSocket Path
      DEVICE_NAME: "XXX"      # Name des Gerätes
      SIMPLE_API_KEY: "XXX" # ⚠️ HIER API-KEY EINTRAGEN!

      # Signal-Konfiguration
      SIGNAL_SERVER_URL: "XXX"  # Signal-Server (BITTE ANPASSEN)
      SIGNAL_RECEIVE_NUMBER: "XXX"         # Eigene Signal-Nummer (Empfang) (BITTE ANPASSEN)
      SIGNAL_SEND_NUMBER: "XXX"           # Eigene Signal-Nummer (Versand) (BITTE ANPASSEN)
      SIGNAL_RECIPIENT_NUMBER: "XXX"      # Standard-Empfänger (BITTE ANPASSEN)
      SIGNAL_VERIFY_SSL: "False"                      # Auf "True" setzen, wenn Zertifikate gültig sind

